import "./globals.css";
import Header from "./_partials/header"

export const metadata = {
  title: "hobbysiege",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}