import "./globals.css";
import Header from "./_partials/header";
import Footer from "./_partials/footer";

export const metadata = {
  title: "hobbysiege",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}