import "./globals.css";
import Header from "./partials/header"

export const metadata = {
  title: "hobbysiege",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div>
          <Header />
        </div>
        <div>
          {children}
        </div>
      </body>
    </html>
  );
}